# vim: ts=2
---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
    
  
  vars:
    vHome: /home/vagrant
    mysql_root_password: 'devops@2022'
    ansible_python_interpreter: /usr/bin/python3
    db_user_root : root
    db_user: devops
    db_pass: devops@2022
    db_name: devops
    path_to_my_sql_files: /vagrant_scripts
    sonar_db_user: sonar
    sonar_db_password: 

  

  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present

    - name: Set up Postgres 14 repo
      shell: |
        echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list 
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt install postgresql postgresql-contrib -y
        sudo systemctl enable postgresql
        sudo systemctl start postgresql
      args:
        warn: no
        
    - name: "Create sonarqube database"
      postgresql_db:
        state: present
        name: sonarqube
      become: yes
      become_user: postgres

   